### ISSUE TITLE
Missing BullyAE_DDS2TEX.py

### ISSUE THREAD

**Issue by santiago046** [EdnessP/scripts#2]
In a [YouTube video](https://youtu.be/jzdKghSntYo) I found this script and noticed that it's missing from your repository — that's how I got here by the way.

**Comment by EdnessP** [comment]
It was removed due to scammers reselling it for insane amounts of money.

**Comment by santiago046** [comment]
Oh… I understand. Just a script and people take advantage of it to sell what is not theirs.
